using System;
using System.Collections.Generic;
using System.Text;
using System.Globalization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;


//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using prueba1Proyecto.Class;
//
//    var clienteRegistro = ClienteRegistro.FromJson(jsonString);

// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using prueba1Proyecto.Class;
//
//    var clienteRegistro = ClienteRegistro.FromJson(jsonString);

namespace prueba1Proyecto.Class
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ClienteRegistro
    {
        [JsonProperty("ClienteRegistro")]
        public List<ClienteRegistroElement> ClienteRegistroClienteRegistro { get; set; }
    }

    public partial class ClienteRegistroElement
    {
        [JsonProperty("Id")]
        public string Id { get; set; }

        [JsonProperty("Name")]
        public string Name { get; set; }

        [JsonProperty("LastName")]
        public string LastName { get; set; }

        [JsonProperty("address1")]
        public string Address1 { get; set; }

        [JsonProperty("address2")]
        public string Address2 { get; set; }

        [JsonProperty("address3")]
        public string Address3 { get; set; }

        [JsonProperty("Bday")]
        public string Bday { get; set; }

        [JsonProperty("Mail")]
        public string Mail { get; set; }

        [JsonProperty("Password")]
        public string Password { get; set; }

        [JsonProperty("Phone")]
        public string Phone { get; set; }
    }

    public partial class ClienteRegistro
    {
        public static ClienteRegistro FromJson(string json) => JsonConvert.DeserializeObject<ClienteRegistro>(json, prueba1Proyecto.Class.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this ClienteRegistro self) => JsonConvert.SerializeObject(self, prueba1Proyecto.Class.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}

